const instagramFeed = [
  {
    id: 1,
    username: "food.explorer",
    time: "1h",
    profileImg: "https://i.imgur.com/2d9NhjQ.jpg",
    postImg: "https://i.imgur.com/wnJYH4M.jpg",
    mutualFrndImg1: "https://i.imgur.com/UrKxU9N.jpg",
    mutualFrndImg2: "https://i.imgur.com/q8QdU8A.jpg",
    likeCount: "2, 00, 000",
    caption: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    commentCount: "100",
  },
  {
    id: 2,
    username: "nature.lover",
    time: "1h",
    profileImg: "https://i.imgur.com/IXo2HbF.jpg",
    postImg: "https://i.imgur.com/YnL3JbA.jpg",
    mutualFrndImg1: "https://i.imgur.com/UkFVpLD.jpg",
    mutualFrndImg2: "https://i.imgur.com/IKMF4lh.jpg",
    likeCount: "2, 00, 000",
    caption:
      "Many touriest came nepal from all over the world to explore the beauty of the land & see the amazing natural places.",
    commentCount: "100",
  },
  {
    id: 3,
    username: "reelsofworld",
    time: "1h",
    profileImg: "https://i.imgur.com/L6lYRLu.jpg",
    postImg: "https://i.imgur.com/ZNH9TLD.jpg",
    mutualFrndImg1: "https://i.imgur.com/J2PZhXW.jpg",
    mutualFrndImg2: "https://i.imgur.com/2OZF8Cq.jpg",
    likeCount: "2, 00, 000",
    caption: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    commentCount: "100",
  },
  {
    id: 4,
    username: "carlover",
    time: "1h",
    profileImg: "https://i.imgur.com/RpRt3HS.jpg",
    postImg: "https://i.imgur.com/VyAdJ8k.jpg",
    mutualFrndImg1: "https://i.imgur.com/R02yQHY.jpg",
    mutualFrndImg2: "https://i.imgur.com/a1rlW1e.jpg",
    likeCount: "2, 00, 000",
    caption:
      "Many touriest came nepal from all over the world to explore the beauty of the land & see the amazing natural places.",
    commentCount: "100",
  },
  {
    id: 5,
    username: "godness",
    time: "1h",
    profileImg: "https://i.imgur.com/M2D5DVa.jpg",
    postImg: "https://i.imgur.com/KPqEedI.jpg",
    mutualFrndImg1: "https://i.imgur.com/EqLW4rP.jpg",
    mutualFrndImg2: "https://i.imgur.com/HgyEwcN.jpg",
    likeCount: "2, 00, 000",
    caption: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    commentCount: "100",
  },
];

export default instagramFeed;
